[features]
seeds = false
[programs.localnet]
solana_programs = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/ian038/.config/solana/id.json"

[scripts]
test = "node tests/solana-programs.js"

[test]
startup_wait = 100000