[features]
seeds = false
[programs.devnet]
solana_programs = "uzL3KSjomggYpSDzM5wcsW8EDLyy6BrMWorjAFuQgtq"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/ian038/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"

[test]
startup_wait = 100000